In [8]:
import pandas as pd

In [9]:
product = pd.read_csv('Datos looks\product.csv')
brand = pd.read_csv('Datos looks//brand.csv')
color = pd.read_csv('Datos looks\color.csv')
feature_value_family = pd.read_csv('Datos looks//feature_value_family.csv')
feature_value= pd.read_csv('Datos looks//feature_value.csv')
feature= pd.read_csv('Datos looks//feature.csv')
product_feature_value_qualifier = pd.read_csv('Datos looks\product_feature_value_qualifier.csv')
product_feature_value = pd.read_csv('Datos looks\product_feature_value.csv')
product_variant = pd.read_csv('Datos looks\product_variant.csv')
season= pd.read_csv('Datos looks//season.csv')
size = pd.read_csv('Datos looks//size.csv')

In [10]:
id = '6b223664-ce8c-4716-958c-6593903aa06b'

In [11]:
product.shape

(2932, 7)

In [12]:
tabla1 = pd.merge(product, brand, how='left', left_on='brand_id', right_on='id', suffixes=['','y'])
tabla1 = tabla1.drop(columns=['idy'])
tabla1.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0
1,6e6b4255-006a-4d13-b312-3b1426290d8e,ce8d442c-e662-44f8-a130-2e436f119ede,6598b655-3e19-448c-8b4f-ff6a29447b34,P1393,9727,Poly Pant deeluxe,"[""LOOKIERO""]",BRAND117,NO_MAINSTREAM,0
2,6549c1b1-989e-432a-bdc9-b603c438b310,cfca4b92-12a6-411c-a62a-a874d00aa735,1b93b30c-833f-45a8-ba69-c21d2e7f4824,J1738,16138,Onleden Sweater knt,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0
3,dace6963-7e84-4cef-a153-3c6fb29cc7c3,1600fb81-6f8b-4fa2-9ae2-a33420125939,c6b81db8-29ed-43d6-b14d-0fd913d7ce36,K892,11621,Cerise Jacket print,"[""LOOKIERO""]",BRAND15,WHOLE_SALE,0
4,d6679919-7a49-4edd-bd04-982289d0e8ac,09358432-a44c-4cb4-b8e6-bf51b403bf39,c59807ac-0362-4078-94b0-37ea3df6cdd0,S2517,14076,Auttum Shirt hippie,"[""LOOKIERO""]",BRAND4,WHOLE_SALE,0

In [13]:
tabla1.shape

(2932, 10)

In [14]:
tabla2 = pd.merge(tabla1, product_variant, how='left', right_on='product_id', left_on='id', suffixes=['', '_variant'])
tabla2 = tabla2.drop(columns=['product_id'])
tabla2.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number,id_variant,barcode,color_id,legacy_id_variant,season,size_id,stock,publishable
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,fbc2f719-e038-4243-892c-7bd2ca6e80b5,740661,6183657f-3a82-449d-aa6a-a14e96b0e9dd,\N,8,a1b735a2-d6e2-4bc8-8502-ccab18802622,0,t
1,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,1920105d-0671-412b-b09f-ef1c983f2be5,740647,6183657f-3a82-449d-aa6a-a14e96b0e9dd,\N,8,77df887d-f7da-42bd-9ebf-a5a2ca57974f,0,t
2,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,a3a0144e-7aa5-4572-b513-285059a14735,740630,6183657f-3a82-449d-aa6a-a14e96b0e9dd,\N,8,0190622f-f028-42a8-b50e-ce310e8a9700,0,t
3,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,c85666c0-a8ba-42f4-a30f-17687ad51ff5,740708,a4902902-49e1-4132-af75-982ab7afec9d,\N,8,cbbdcb38-00c1-4ec2-a76b-cdf948cc81ce,0,t
4,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,93db9797-3a66-4889-be9c-5d3522da96a1,740739,f570d998-7aa4-442d-8a2f-7885bd499729,\N,8,0190622f-f028-42a8-b50e-ce310e8a9700,0,t

In [15]:
tabla3 = pd.merge(tabla2, color, how='left', right_on='id', left_on='color_id', suffixes=['', '_color'])
tabla3 = tabla3.drop(columns=['id_color'])
tabla3.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number,...,color_id,legacy_id_variant,season,size_id,stock,publishable,code,hexadecimal,name_color,parent
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,6183657f-3a82-449d-aa6a-a14e96b0e9dd,\N,8,a1b735a2-d6e2-4bc8-8502-ccab18802622,0,t,C2,000000,black,\N
1,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,6183657f-3a82-449d-aa6a-a14e96b0e9dd,\N,8,77df887d-f7da-42bd-9ebf-a5a2ca57974f,0,t,C2,000000,black,\N
2,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,6183657f-3a82-449d-aa6a-a14e96b0e9dd,\N,8,0190622f-f028-42a8-b50e-ce310e8a9700,0,t,C2,000000,black,\N
3,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,a4902902-49e1-4132-af75-982ab7afec9d,\N,8,cbbdcb38-00c1-4ec2-a76b-cdf948cc81ce,0,t,C15,DFC8B2,beige,\N
4,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,f570d998-7aa4-442d-8a2f-7885bd499729,\N,8,0190622f-f028-42a8-b50e-ce310e8a9700,0,t,C27,B94600,rust,e9f37c85-a5bd-4f52-a891-b575ab2f787f

In [16]:
tabla4= pd.merge(tabla3, size, how='left', right_on='id', left_on='size_id', suffixes=['', '_drop'])
tabla4 = tabla4.drop(columns=['id_drop'])
tabla4.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number,...,publishable,code,hexadecimal,name_color,parent,europe,lookiero,uk,"""order""",visual_order
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,t,C2,000000,black,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26
1,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,t,C2,000000,black,\N,"{""size"": ""38"", ""format"": ""38""}","{""size"": ""M"", ""format"": ""M""}","{""size"": ""10"", ""format"": ""10""}",38,16
2,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,t,C2,000000,black,\N,"{""size"": ""36"", ""format"": ""36""}","{""size"": ""S"", ""format"": ""S""}","{""size"": ""8"", ""format"": ""8""}",24,11
3,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,t,C15,DFC8B2,beige,\N,"{""size"": ""40"", ""format"": ""40""}","{""size"": ""L"", ""format"": ""L""}","{""size"": ""12"", ""format"": ""12""}",51,21
4,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,t,C27,B94600,rust,e9f37c85-a5bd-4f52-a891-b575ab2f787f,"{""size"": ""36"", ""format"": ""36""}","{""size"": ""S"", ""format"": ""S""}","{""size"": ""8"", ""format"": ""8""}",24,11

In [17]:
tabla5= pd.merge(tabla4, product_feature_value, how='left', right_on='product_id', left_on='id', suffixes=['', '_feature'])
tabla5 = tabla5.drop(columns=['product_id'])
tabla5.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number,...,hexadecimal,name_color,parent,europe,lookiero,uk,"""order""",visual_order,id_feature,feature_value_id
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,000000,black,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,17180364-12d1-423b-b9f4-ed7d121910d2,b5ce1fed-4c38-4920-90b5-42e46f971e97
1,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,000000,black,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,f5ff2b4f-ae17-4f53-b18b-9d269471790a,cc2da427-ae37-4e83-8728-d9dc93539806
2,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,000000,black,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,bf200d63-0e15-4ea8-a5c7-6c9b65369bc9,c42e949a-06dd-4888-b7be-b73e2c88b541
3,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,000000,black,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,28a885d6-cc6e-4d12-8b9c-29a4dec5f402,e5badc68-5360-414e-beba-b10ed1a56629
4,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,000000,black,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,beaee8ca-0ce2-4041-bc7e-3574f14c3d70,877425b0-3bed-4c99-97de-09a53c508058

In [18]:
tabla6= pd.merge(tabla5, feature_value, how='left', right_on='id', left_on='feature_value_id', suffixes=['', '_drop'])
tabla6 = tabla6.drop(columns=['id_drop'])
tabla6.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number,...,parent,europe,lookiero,uk,"""order""",visual_order,id_feature,feature_value_id,value,feature_id
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,17180364-12d1-423b-b9f4-ed7d121910d2,b5ce1fed-4c38-4920-90b5-42e46f971e97,cardigan,0ccb5374-db8c-4dbb-afae-6b2652af170d
1,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,f5ff2b4f-ae17-4f53-b18b-9d269471790a,cc2da427-ae37-4e83-8728-d9dc93539806,ribbed,10e14a5d-39b6-4045-93cc-1574f68606ec
2,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,bf200d63-0e15-4ea8-a5c7-6c9b65369bc9,c42e949a-06dd-4888-b7be-b73e2c88b541,two,604b76cd-27a8-45ef-8734-618639ff331a
3,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,28a885d6-cc6e-4d12-8b9c-29a4dec5f402,e5badc68-5360-414e-beba-b10ed1a56629,without_closing,2e2a28f9-566d-419f-9081-cc9061324110
4,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,\N,"{""size"": ""42"", ""format"": ""42""}","{""size"": ""XL"", ""format"": ""XL""}","{""size"": ""14"", ""format"": ""14""}",69,26,beaee8ca-0ce2-4041-bc7e-3574f14c3d70,877425b0-3bed-4c99-97de-09a53c508058,cold_season,6e518bda-2083-41b9-89c0-6c52392261d3

In [19]:
df_final= pd.merge(tabla6, feature, how='left', left_on='feature_id', right_on='id', suffixes=['','_drop'])
df_final = df_final.drop(columns=['id_drop'])
df_final.head()

,id,brand_id,family_id,"""group""",legacy_id,title,channels,name,origin,number,...,"""order""",visual_order,id_feature,feature_value_id,value,feature_id,name_drop,type,multiple,unit
0,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,69,26,17180364-12d1-423b-b9f4-ed7d121910d2,b5ce1fed-4c38-4920-90b5-42e46f971e97,cardigan,0ccb5374-db8c-4dbb-afae-6b2652af170d,top_type,STRING,f,\N
1,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,69,26,f5ff2b4f-ae17-4f53-b18b-9d269471790a,cc2da427-ae37-4e83-8728-d9dc93539806,ribbed,10e14a5d-39b6-4045-93cc-1574f68606ec,finishing,STRING,t,\N
2,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,69,26,bf200d63-0e15-4ea8-a5c7-6c9b65369bc9,c42e949a-06dd-4888-b7be-b73e2c88b541,two,604b76cd-27a8-45ef-8734-618639ff331a,adventurous,STRING,t,\N
3,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,69,26,28a885d6-cc6e-4d12-8b9c-29a4dec5f402,e5badc68-5360-414e-beba-b10ed1a56629,without_closing,2e2a28f9-566d-419f-9081-cc9061324110,closing,STRING,t,\N
4,5f5c4a50-557a-4d53-9e81-cc72fdd18fbf,cfca4b92-12a6-411c-a62a-a874d00aa735,141f32d6-a5af-49bf-b019-fd28354977f1,J1214,\N,Onljade Cardigan knit,"[""LOOKIERO""]",BRAND119,MAINSTREAM,0,...,69,26,beaee8ca-0ce2-4041-bc7e-3574f14c3d70,877425b0-3bed-4c99-97de-09a53c508058,cold_season,6e518bda-2083-41b9-89c0-6c52392261d3,weather,STRING,t,\N

In [20]:
df_final.shape

(620712, 35)